修正获取Gist内容的错误处理，确保在获取无效内容时输出错误信息并退出

diff --git a/.github/workflows/weread-heatmap.yml b/.github/workflows/weread-heatmap.yml
--- a/.github/workflows/weread-heatmap.yml
+++ b/.github/workflows/weread-heatmap.yml
@@ -27,11 +27,19 @@ jobs:
         run: |
           # 获取JSON文件内容
           JSON_DATA=$(curl -s "$GIST_URL")
+
+           # 检查是否成功获取版本号
+          if [ -z "$JSON_DATA" ] || [ "$JSON_DATA" = "null" ]; then
+            echo "Failed to get valid gist content."
+            exit 1
+          fi
           
           # 使用jq解析并导出变量
           echo "USER_VID=$(echo $JSON_DATA | jq -r '.vid')" >> $GITHUB_ENV
           echo "REQUEST_BODY=$(echo $JSON_DATA | jq -r '.requestBody')" >> $GITHUB_ENV
           echo "REQUEST_HEADERS=$(echo $JSON_DATA | jq -r '.headers')" >> $GITHUB_ENV
+
+
       - name: Generate heatmap
         env:
           USER_VID: ${{ env.USER_VID }}
